version: "3.7"

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-4000}:4000"
    volumes:
      - ./:/app:cached
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db: {}
